version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: always
    volumes:
      - ./backend/database.sqlite:/usr/src/app/database.sqlite
    env_file:
      - ./.env

  frontend:
    build:
      context: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend