version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database.sqlite:/usr/src/app/database.sqlite
    env_file:
      - ./.env

  frontend:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - backend
